### ISSUE TITLE
ddcutil 1.0.0

### ISSUE THREAD

**Issue by yochananmarqos** [FedeDP/Clightd#66]
Just for fun I tried building with `ddcutil` [1.0.0](https://github.com/rockowitz/ddcutil/releases/tag/v1.0.0), but alas!

```
--- The C compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Checking for modules 'libudev;libmodule>=5.0.0;libjpeg'
--   Found libudev, version 247
--   Found libmodule, version 5.0.1
--   Found libjpeg, version 2.0.6
-- Checking for module 'polkit-gobject-1'
--   Found polkit-gobject-1, version 0.118
-- Checking for module 'dbus-1'
--   Found dbus-1, version 1.12.20
-- Checking for one of the modules 'libelogind;libsystemd>=221'
-- Checking for modules 'x11;xrandr;libdrm;wayland-client'
--   Found x11, version 1.7.0
--   Found xrandr, version 1.5.2
--   Found libdrm, version 2.4.104
--   Found wayland-client, version 1.19.0
-- GAMMA support enabled
-- Enabled 'wlr-gamma-control-unstable-v1' wayland client protocol
-- Checking for modules 'x11;xext;libdrm;wayland-client'
--   Found x11, version 1.7.0
--   Found xext, version 1.3.4
--   Found libdrm, version 2.4.104
--   Found wayland-client, version 1.19.0
-- DPMS support enabled
-- Enabled 'org_kde_kwin_dpms' wayland client protocol
-- Checking for module 'x11'
--   Found x11, version 1.7.0
-- SCREEN support enabled
-- Enabled 'wlr-screencopy-unstable-v1' wayland client protocol
-- Checking for module 'ddcutil>=0.9.5'
--   Found ddcutil, version 1.0.0
-- DDC support enabled
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.24
-- YOCTOLIGHT support enabled
-- Checking for module 'systemd'
--   Found systemd, version 247
-- Using default value for dbus config dir: /etc/dbus-1/system.d
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/storage/pkgbuilds/clightd-git/src/build
make: Entering directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
make[1]: Entering directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
make[2]: Entering directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
[  6%] Generating org_kde_kwin_dpms-client-protocol.h, org_kde_kwin_dpms-protocol.c
[  6%] Generating wlr-screencopy-unstable-v1-client-protocol.h, wlr-screencopy-unstable-v1-protocol.c
[  9%] Generating wlr-gamma-control-unstable-v1-client-protocol.h, wlr-gamma-control-unstable-v1-protocol.c
Scanning dependencies of target clightd
make[2]: Leaving directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
make[2]: Entering directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
[ 12%] Building C object CMakeFiles/clightd.dir/src/modules/screen.c.o
[ 15%] Building C object CMakeFiles/clightd.dir/src/modules/signal.c.o
[ 18%] Building C object CMakeFiles/clightd.dir/src/main.c.o
[ 21%] Building C object CMakeFiles/clightd.dir/src/modules/idle.c.o
[ 24%] Building C object CMakeFiles/clightd.dir/src/modules/bus.c.o
[ 27%] Building C object CMakeFiles/clightd.dir/src/modules/backlight.c.o
[ 30%] Building C object CMakeFiles/clightd.dir/src/utils/udev.c.o
[ 36%] Building C object CMakeFiles/clightd.dir/src/modules/gamma.c.o
[ 36%] Building C object CMakeFiles/clightd.dir/src/modules/dpms.c.o
[ 45%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/als.c.o
[ 45%] Building C object CMakeFiles/clightd.dir/src/modules/sensor.c.o
[ 45%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/custom.c.o
[ 48%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/camera.c.o
[ 51%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/yoctolight.c.o
[ 54%] Building C object CMakeFiles/clightd.dir/src/utils/polkit.c.o
[ 57%] Building C object CMakeFiles/clightd.dir/src/utils/drm_utils.c.o
[ 60%] Building C object CMakeFiles/clightd.dir/src/utils/wl_utils.c.o
[ 63%] Building C object CMakeFiles/clightd.dir/wlr-gamma-control-unstable-v1-protocol.c.o
[ 69%] Building C object CMakeFiles/clightd.dir/src/modules/gamma_plugins/wl.c.o
[ 69%] Building C object CMakeFiles/clightd.dir/src/modules/gamma_plugins/drm.c.o
[ 72%] Building C object CMakeFiles/clightd.dir/src/modules/gamma_plugins/xorg.c.o
[ 75%] Building C object CMakeFiles/clightd.dir/org_kde_kwin_dpms-protocol.c.o
[ 78%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/drm.c.o
[ 81%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/wl.c.o
[ 84%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/xorg.c.o
[ 87%] Building C object CMakeFiles/clightd.dir/wlr-screencopy-unstable-v1-protocol.c.o
[ 93%] Building C object CMakeFiles/clightd.dir/src/modules/screen_plugins/wl.c.o
[ 93%] Building C object CMakeFiles/clightd.dir/src/modules/screen_plugins/xorg.c.o
[ 96%] Building C object CMakeFiles/clightd.dir/src/modules/screen_plugins/fb.c.o
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/idle.c: In function ‘receive’:
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/idle.c:107:17: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  107 |                 read(msg->fd_msg->fd, &t, sizeof(uint64_t));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/gamma.c: In function ‘receive’:
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/gamma.c:75:9: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   75 |         read(msg->fd_msg->fd, &t, sizeof(uint64_t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/backlight.c: In function ‘convert_sn_to_id’:
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/backlight.c:102:20: warning: implicit declaration of function ‘ddca_create_adlno_display_identifier’; did you mean ‘ddca_create_busno_display_identifier’? [-Wimplicit-function-declaration]
  102 |             return ddca_create_adlno_display_identifier(id1, id2, pdid);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    ddca_create_busno_display_identifier
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/backlight.c: In function ‘receive’:
/mnt/storage/pkgbuilds/clightd-git/src/clightd/src/modules/backlight.c:216:13: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  216 |             read(sc->smooth_fd, &t, sizeof(uint64_t));
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking C executable clightd
/usr/bin/ld: CMakeFiles/clightd.dir/src/modules/backlight.c.o: in function `convert_sn_to_id.constprop.0':
backlight.c:(.text+0x3be): undefined reference to `ddca_create_adlno_display_identifier'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/clightd.dir/build.make:547: clightd] Error 1
make[2]: Leaving directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/clightd.dir/all] Error 2
make[1]: Leaving directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
make: *** [Makefile:171: all] Error 2
make: Leaving directory '/mnt/storage/pkgbuilds/clightd-git/src/build'
```

**Comment by FedeDP** [comment]
Hi! Thanks for reminding me :) 
I will add support for ddcutil 1.0.0 asap!

**Comment by FedeDP** [comment]
Ok clightd now builds with ddcutil 1.0.0!

**Comment by yochananmarqos** [comment]
Thanks!

**Comment by asmarcz** [comment]
Hello, I have just experienced this on my Manjaro after the latest 09 Feb update. How long do you expect before a new clightd release that gets propagated to stable AUR package? Other workaround than switching to clightd-git?

I am currently stuck on `error while loading shared libraries: libddcutil.so.3`. Thanks
```
asmar$ journalctl -xe
....
Feb 11 19:40:56 asmarManjaro systemd[1]: Starting Bus service to manage various screen related properties (gamma, dpms, backlight)...
░░ Subject: A start job for unit clightd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░
░░ A start job for unit clightd.service has begun execution.
░░
░░ The job identifier is 131248.
Feb 11 19:40:56 asmarManjaro clightd[66041]: /usr/lib/Clightd/clightd: error while loading shared libraries: libddcutil.so.3: cannot open shared object file: No such file or directory
Feb 11 19:40:56 asmarManjaro systemd[1]: clightd.service: Main process exited, code=exited, status=127/n/a
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░
░░ An ExecStart= process belonging to unit clightd.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 127.
Feb 11 19:40:56 asmarManjaro systemd[1]: clightd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░
░░ The unit clightd.service has entered the 'failed' state with result 'exit-code'.
Feb 11 19:40:56 asmarManjaro systemd[1]: Failed to start Bus service to manage various screen related properties (gamma, dpms, backlight).
░░ Subject: A start job for unit clightd.service has failed
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░
░░ A start job for unit clightd.service has finished with a failure.
░░
░░ The job identifier is 131248 and the job result is failed.
```

**Comment by yochananmarqos** [comment]
@asmarcz Install the `clight-git` AUR package for now. It will pull in `clightd-git` as dependency.

**Comment by FedeDP** [comment]
Hi! I plan to release new Clight and Clightd soon enough, may be already this weekend.
In the meantime you can downgrade ddcutil or upgrade to clight(d)-git!
